# Generated by Django 4.2 on 2023-05-13 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Ожидание'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=100, null=True)),
                ('reference_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.referencetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
