# Generated by Django 4.2 on 2023-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_reference_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='info',
            field=models.TextField(),
        ),
    ]
