# Generated by Django 4.2 on 2023-05-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_reference_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Анықтама', 'verbose_name_plural': 'Анықтамалар'},
        ),
    ]
