# Generated by Django 4.2 on 2023-05-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_reference_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencetype',
            options={'verbose_name': 'Анықтама түрі', 'verbose_name_plural': 'Анықтама түрлері'},
        ),
    ]
