# Generated by Django 4.2 on 2023-05-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_alter_referencetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Справка', 'verbose_name_plural': 'Справки'},
        ),
        migrations.AlterModelOptions(
            name='referencetype',
            options={'verbose_name': 'Тип справки', 'verbose_name_plural': 'Типы справки'},
        ),
    ]
