# Generated by Django 4.2 on 2023-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_alter_reference_options_alter_referencetype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
